### ISSUE TITLE
The "build and publish tag" action doesn't run automatically

### ISSUE THREAD

**Issue by rokf** [Unleash/unleash-docker-community#35]
### Describe the bug

If we compare the tags that are available on this repository and the tags that are available on Docker Hub we can see that not all of them can be found there. The last few are missing.

I've noticed that there's a GitHub Action file that should be building Docker images, tagging them and pushing them on every tag push in https://github.com/Unleash/unleash-docker-community/blob/main/.github/workflows/buildtags.yml but it doesn't seem to work.

Were the new tags perhaps created through the GitHub UI instead of being pushed with a local Git client?

If we take a look at https://github.com/Unleash/unleash-docker-community/actions/workflows/buildtags.yml we can see that there haven't been any runs for the last two months.

### Subscription type

Open source

### Hosting type

Self-hosted

**Comment by pransh15** [comment]
Hi @rokf, thanks for reporting the bug! 🙏 
I'll take it to the team, and we'll get back to you soon.

**Comment by ZanMarolt** [comment]
To expand on the bug and the current workflow for the community vs official docker repositories:

- Currently the tags are pushed on every push to the main branch (community)
- The renovate bot handles and opens up version upgrade pull requests automatically (not sure what is the frequency, but looks like it doesn't check every day)
- The renovate bot pull requests are not merged automatically but need to be approved first - I try my best to merge them as soon as possible
- The new tags are pushed automatically by a github action, @rokf see github tag action: https://github.com/Unleash/unleash-docker-community/actions/workflows/createtag.yml The one you're looking at is deprecated/not used

Due to this the official and community docker images are often out of sync...

Any suggestions greatly appreciated :)

**Comment by rokf** [comment]
Could the mentioned GitHub Action be updated with the functionality to build and push Docker images to Docker Hub with every tag that it creates in this repository on GitHub? We're having problems with missing Docker tags, not Git tags.

**Comment by ZanMarolt** [comment]
It is possible but we would need to remove approvals for dependabot opened PRs so that they are merged automatically or automate the process some other way without the dependabot by an action, which would be merged automatically.

I do wonder though, do you need to be on the latest version all the time? Why not synchronize the versions by the one that is available in both official and community docker hub repos?

**Comment by rokf** [comment]
This is our primary version since this one supports Azure AD, which we have to use.

The two main reasons to why we'd like to stay up to date with the versions are:

- we'd like to keep up with bug fixes and security patches
- we find it easier to upgrade frequently, this way (configuration, deployment) changes that'd be required on our side can't really accumulate, there's a smaller chance that they could cause trouble

I'll discuss with my team if we're perhaps willing to contribute a patch ourselves. If an action runs every time a (matching) Git tag is (manually / automatically - doesn't matter) created on this repository and new images (tags) are built and pushed, that'd be more than enough.

**Comment by ZanMarolt** [comment]
If you were to synchronise the versions, you guys would be behind a week of updates tops, if at all. 😉

But yeah, if you see that a version isn't synchronised you could open up a PR to update the version, still the PR must be approved and merged, then the build will happen automatically. 👍
